import type {
  EnemyDefinition,
  MapConfig,
  TowerDefinition,
  UpgradeDefinition,
} from "./types.js";

export const TOWER_DEFINITIONS: Record<string, TowerDefinition> = {
  defender: {
    id: "defender",
    name: "Defender",
    description: "Frontline resistente para segurar as rotas.",
    cost: 30,
    baseDamage: 6,
    baseRange: 90,
    baseCooldownMs: 900,
  },
  archer: {
    id: "archer",
    name: "Archer",
    description: "DPS de longo alcance com ataque veloz.",
    cost: 35,
    baseDamage: 9,
    baseRange: 150,
    baseCooldownMs: 700,
  },
  mage: {
    id: "mage",
    name: "Mage",
    description: "Dano mágico em área pequena por impacto.",
    cost: 40,
    baseDamage: 12,
    baseRange: 130,
    baseCooldownMs: 1000,
  },
};

export const ENEMY_DEFINITIONS: Record<string, EnemyDefinition> = {
  swarm: {
    id: "swarm",
    name: "Swarmling",
    maxHp: 20,
    speed: 56,
    rewardGold: 6,
    rewardXp: 8,
    contactDamage: 3,
    weight: 45,
  },
  ranged: {
    id: "ranged",
    name: "Rift Archer",
    maxHp: 26,
    speed: 50,
    rewardGold: 8,
    rewardXp: 10,
    contactDamage: 4,
    weight: 22,
  },
  armored: {
    id: "armored",
    name: "Obsidian Guard",
    maxHp: 42,
    speed: 40,
    rewardGold: 12,
    rewardXp: 14,
    contactDamage: 6,
    weight: 18,
  },
  runner: {
    id: "runner",
    name: "Blink Runner",
    maxHp: 16,
    speed: 88,
    rewardGold: 7,
    rewardXp: 9,
    contactDamage: 4,
    weight: 25,
  },
  elite: {
    id: "elite",
    name: "Fracture Champion",
    maxHp: 95,
    speed: 48,
    rewardGold: 24,
    rewardXp: 30,
    contactDamage: 10,
    weight: 8,
  },
  boss: {
    id: "boss",
    name: "Aetherfall Behemoth",
    maxHp: 480,
    speed: 36,
    rewardGold: 120,
    rewardXp: 140,
    contactDamage: 25,
    weight: 0,
    isBoss: true,
  },
};

export const UPGRADE_POOL: UpgradeDefinition[] = [
  {
    id: "iron_focus",
    name: "Iron Focus",
    description: "+4 dano do heroi.",
    rarity: "common",
    effects: [{ kind: "hero_damage_flat", amount: 4 }],
  },
  {
    id: "long_step",
    name: "Long Step",
    description: "+30 velocidade de movimento.",
    rarity: "common",
    effects: [{ kind: "hero_move_speed_flat", amount: 30 }],
  },
  {
    id: "tower_forging",
    name: "Tower Forging",
    description: "Torres causam +18% dano.",
    rarity: "common",
    effects: [{ kind: "tower_damage_pct", amountPct: 18 }],
  },
  {
    id: "rapid_bolts",
    name: "Rapid Bolts",
    description: "Torres atacam 15% mais rapido.",
    rarity: "common",
    effects: [{ kind: "tower_cooldown_pct", amountPct: 15 }],
  },
  {
    id: "extended_sight",
    name: "Extended Sight",
    description: "+30 alcance de ataque do heroi.",
    rarity: "common",
    effects: [{ kind: "hero_attack_range_flat", amount: 30 }],
  },
  {
    id: "reinforced_slots",
    name: "Reinforced Slots",
    description: "+1 limite de torres.",
    rarity: "rare",
    effects: [{ kind: "tower_slot_flat", amount: 1 }],
  },
  {
    id: "greedy_aura",
    name: "Greedy Aura",
    description: "+20% ouro recebido.",
    rarity: "rare",
    effects: [{ kind: "gold_gain_pct", amountPct: 20 }],
  },
  {
    id: "second_wind",
    name: "Second Wind",
    description: "Recupera 25 de vida.",
    rarity: "rare",
    effects: [{ kind: "heal_flat", amount: 25 }],
  },
  {
    id: "monolith_patch",
    name: "Monolith Patch",
    description: "Recupera 15 de vida da base.",
    rarity: "rare",
    effects: [{ kind: "base_repair_flat", amount: 15 }],
  },
  {
    id: "tactical_reroll",
    name: "Tactical Reroll",
    description: "+1 token de reroll para upgrades futuros.",
    rarity: "epic",
    effects: [{ kind: "reroll_token_flat", amount: 1 }],
  },
];

export const MAPS: MapConfig[] = [
  {
    id: "wardens-field",
    name: "Wardens Field",
    width: 1280,
    height: 720,
    heroSpawn: { x: 260, y: 340 },
    basePosition: { x: 1130, y: 340 },
    paths: [
      [
        { x: 40, y: 120 },
        { x: 320, y: 120 },
        { x: 320, y: 280 },
        { x: 760, y: 280 },
        { x: 760, y: 340 },
        { x: 1130, y: 340 },
      ],
      [
        { x: 40, y: 560 },
        { x: 420, y: 560 },
        { x: 420, y: 420 },
        { x: 900, y: 420 },
        { x: 900, y: 340 },
        { x: 1130, y: 340 },
      ],
    ],
    towerSlots: [
      { x: 220, y: 220 },
      { x: 220, y: 470 },
      { x: 430, y: 350 },
      { x: 620, y: 200 },
      { x: 640, y: 500 },
      { x: 860, y: 320 },
      { x: 980, y: 220 },
      { x: 980, y: 500 },
    ],
  },
];

export const DEFAULT_MAP = MAPS[0];
